#!/bin/bash

echo "Starting to commit!"
git branch
git add .

echo -e "Do you want to commit?Y/N"
read commit_choice

# Reset if n come up with something better
if [ $commit_choice = "N" ]
then
	git reset
elif [ $commit_choice = "n" ]
then
	git reset
elif [ $commit_choice = "No" ]
then
	git reset
elif [ $commit_choice = "no" ]
then
	git reset
elif [ $commit_choice = "NO" ]
then
	git reset
fi

if [ $commit_choice = "y" ]
then
	echo -e "Please enter your commit comments"
	read comments
fi

if [ -n "$comments" ]
then
	git commit -m "$comments"
	echo -e "Branch name?"
	read branch
	if [ -n "$branch" ]
	then
		git push origin $branch
		echo "Cheers"
	fi
fi


